<?php
//遠傳電信回傳碼、錯誤代碼 "99999" 為自行定義當網路無法正確連現實之錯誤代碼
$return_code = array(
	'00000' => '已發送',
	'00020' => 'XML validation errors. Core reason is {0}.',
	'00030' => 'SysId not Found.',
	'00060' => 'Invalid SrcAddress.',
	'00070' => 'Invalid DestAddress.',
	'00080' => 'Invalid Base64 String.',
	'00090' => 'Empty MediaContent for file{0}.',
	'00100' => 'No MediaName found for theMediaContent.',
	'00110' => 'Invalid MediaName for the MediaContent.',
	'00120' => 'No PresentationMedia found.',
	'00130' => 'Invalid MediaContent.',
	'00150' => 'SmsBody Length is longer than allowed length.',
	'00160' => 'WapDesc + WapUrl length is longer than allowed length{0}.',
	'00170' => 'MmsSubject length is longer than allowed length. Ascii:{0} characters and non-ascii:{1} characters.',
	'00180' => 'Invalid WapUrl',
	'00190' => 'Invalid format for ExpiryMinutes.',
	'00200' => 'ExpiryMinutes have exceeded the supported maximum expiry minutes of {0}.',
	'00210' => 'SrcAddress does not belong to the account.',
	'00240' => 'Service unavailable. Code = {0}.',
	'00250' => 'Spam check failed.',
	'00260' => 'Not enough quota to send request.',
	'00270' => 'You are currently prevented from submitting messages at this time.',
	'00280' => 'Message type not supported.',
	'00290' => 'Your account is no longer active.',
	'00300' => 'You are not allowed to use HTTP API.',
	'00310' => 'Query/Retrieve API requests exceed maximum allowed per hour.',
	'00320' => 'Submit API requests exceed maximum B parties allowed per hour.',
	'00330' => 'Combined MmsPresentation + all Media elements size exceed {0}kb.',
	'00340' => 'You are not allowed to use FirstFailFlag.',
	'00350' => 'You are not allowed to receive {0} DR.',
	'00360' => 'You have exceeded the maximum allowed destination address of {0}.',
	'00370' => 'You are not allow to query Dr.',
	'00380' => 'Reserved characters <, >, or & is found, please correct and resend.',
	'00390' => 'Invalid MessageId.',
	'00410' => 'Invalid login account.',
	'00420' => 'Invalid StartDate.',
	'00430' => 'Invalid EndDate.',
	'00440' => 'Date range exceeded the maximum allowed period.',
	'00450' => 'Source addresses exceeded the maximum allowed numbers.',
	'00460' => 'Allow only one a date range report request in processing, please try again later.',
	'99999' => '無法建立網路連線'
) ;
##
?>